name: List Project
on: 
  push:
    branches:
        - github-actions/initial
jobs:
    listproject:
        runs-on: macos-latest
        steps:
            - name: Build apk
              run: flutter build apk
   
