# 01. INTALL JAVA
# 02. INSTALL FLUTTER
# 03. GENERAR UNA APK
# 04. GUARD
#     - flutter analyze
#     - flutter test
# 05. GENERAR IPA
#     - INSTALAR PERFIL TEMPORAL
#     - INSTALAR CERTIFICADOS
#     - CONFIGURAR KEYCHAIN
# 06. APP DISTRIBUTION CLI
#     - firebase tools

name: FLUTTER_MASTER
on:
  push:
    branches:
      - github-action

jobs:
  flutter_master_dev:
    runs-on: macos-latest
    steps:
      - name: COPY .
        uses: actions/checkout@v4
      - run: echo '${{vars.HELLO_MOM}}'
      - run: echo '${{secrets.HELLO_MOM}}'
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
